### ISSUE TITLE
TODO list follow-up (removals)

### ISSUE THREAD

**Issue by heinermann** [JDongian/bwapi3to4#4]
List of things you can ignore:
#### Changes in BWAPI 4.1.0 Beta
- [ ] The video commands have been removed _(this was for in-game "/commands" and is not relevant)_
#### Changes in BWAPI 4.0.0 Beta (r4350)
- [ ] getClientInfo/setClientInfo are now available to all Interface classes, and also take an optional parameter that acts as a key _(this is an enhancement, the old methods should still work)_
- [ ] All types' enumerations are now available (for switch case usage) and are accessed by Types::Enum (Example: UnitTypes::Enum::Terran_Marine) _(This is an addition and is not relevant to conversion)_
- [ ] Instead of using Game::printf, you may use BWAPI::Broodwar like you would std::cout, using operator << _(Game::printf works the same as before so this is not relevant)_
- [ ] Using Special_Start_Location in canBuildHere will ignore units that are occupying the space while still checking for resource distance _(This is an enhancement and is not relevant)_
- [ ] getTextColor now returns a char instead of an int so that it is printed correctly when used with ostream::operator << _(Nothing needs to be done for this. The char will upcast to an int implicitly if it was ever used that way.)_
- [ ] Unit count functions now take a default parameter of AllUnits _(Enhancement and not relevant.)_
- [ ] Unit commands are now more strict _(This is an internal change and does not affect the API. It simply prevents sending commands to BW that are expected to fail)_
- [ ] getResources now returns the last-known resource amount when the unit becomes inaccessible _(This is an enhancement that shouldn't affect existing logic.)_
